title: Arctic Shores Training Security
activity_type: Work based learning
start_date: '2017-12-07'
end_date: '2017-12-07'
activity_url: ''
learning_hours: '1'
tags: ''
activity_description: Security training delivered by Jorn on best practice. Included
  choices for passwords, two-factor authentication, public wifi and laptop encryption.
benefit_to_practice: Jorn's presentation taught me how to ensure that Arctic Shores
  data is kept secure. As part of the session, I set up two-factor authentication
  on my mobile and encrypted my work laptop. We also discussed accessing the DataHub
  over public wifi.
benefit_to_users: Arctic Shores stores some personal data of the users. Therefore,
  we have a duty to follow UK guidance and best practice to keep their data secure.
