# Detailed Report: `r y`

```{r}
df_mini = 
  df  %>% 
  filter(year == y)

```

In `r y` I completed `r sum(df_mini$learning_hours)` hours of CPD training, across `r length(unique(df_mini$activity_type))` categories.


```{r}
df_mini %>% 
  group_by(activity_type) %>% 
  summarise(total_hours = sum(learning_hours)) %>%
  arrange(desc(total_hours)) %>% 
  gt() %>% 
  cols_label(
    activity_type = md("**Activity Type**"),
    total_hours = md("**Learning Hours**")
  ) %>% 
  grand_summary_rows(
    columns = vars(total_hours),
    fns = list(
      Total = ~sum(.)),
    formatter = fmt_number,
    use_seps = FALSE
  )
```

## Tags analysis


## Benefits Gained report

```{r}
df_mini %>% 
  #arrange(start_date) %>%
  select(title, learning_hours, activity_description, benefit_to_practice, benefit_to_users) %>% 
  gt() %>% 
  cols_label(
    title = md("**Title**"),
    learning_hours = md("**Learning Hours**"),
    activity_description = md("**Activity Description**"),
    benefit_to_practice = md("**Benefit to Practice**"), 
    benefit_to_users = md("**Benefit to Users**")
  )  %>% 
  cols_width(
    vars(title) ~ px(100),
    vars(learning_hours) ~ px(100),
    vars(activity_description) ~ px(300),
    starts_with("Benefit") ~ px(300),
  ) %>%
  tab_style(
    style = cell_text(size = px(11)),
    locations = cells_body(
      columns = everything()
    )
  ) %>% 
  tab_options(
    container.width = px(1200)
  )
```
