title: Responsive Web Applications
activity_type: Formal / educational
start_date: '2023-10-12'
end_date: '2023-10-12'
activity_url: ''
learning_hours: '3'
tags: ''
activity_description: |
  A formal workshop taught by Dr Keith Newman. 
  I learned what makes web applications frustrating to use, and tools to make the applications I build more responsive to the user.
benefit_to_practice: |
  I regularly build web applications but I didn't really understand about HTML and JS.
  Keith helped me understand how the design choices I make will affect my users.
benefit_to_users: |
  I will use the skills I learnt to make more responsive web applications for my users.
